### PR TITLE
Consistent Typehints

### PR DESCRIPTION
**Pull request by fwuermseher**
Modifications to typehints and docstrings that work towards closing #23: 

* Added missing typehints, or modified inconsistent ones. 
* Added input validation for `study._params`.
* Removed typehints from the docstrings, as this causes duplicates in the docs, as mkdocs parses the typehints as well. (image below).
* For consistency with `n_trials`, `n_evaluations` etc., renamed `nsteps` -> `n_steps`

image

### CODE REVIEW

File: py-evobandits/python/evobandits/study/study.py [hunk 1]
```diff
@@ -53,35 +53,35 @@ def __init__(self, seed: int | None = None, algorithm=ALGORITHM_DEFAULT) -> None
             raise TypeError(f"Seed must be integer: {seed}")
 
         self.seed: int | None = seed
-        self.algorithm = algorithm  # ToDo Issue #23: type and input validation
-        self.objective: Callable | None = None  # ToDo Issue #23: type and input validation
-        self.params: ParamsType | None = None  # ToDo Issue #23: Input validation
+        self.algorithm: EvoBandits = algorithm
+        self.objective: Callable | None = None  # type: ignore
+        self.params: ParamsType | None = None  # type: ignore
```
Comment (tnkuehne) [inline py-evobandits/python/evobandits/study/study.py:58]:
```suggestion
```
Can't they just be left out, instead of initialising them ugly? I then get no type errors

**Review by tnkuehne — CHANGES_REQUESTED** [review]

File: py-evobandits/python/evobandits/study/study.py (hunk 1 above)
Comment (fwuermseher) [reply py-evobandits/python/evobandits/study/study.py:58]: Theoretically yes, but that would be somewhat of a bad practice, because it raises "AttributeError: 'Study' object has no attribute 'objective'" if someone tries to access the attributes objective manually before running study optimize.

Instead of initializing "ugly", the attributes can be implemented as properties instead.

**Review by tnkuehne — APPROVED** [review]
